title: Azurebrains
description: Blog sobre Tecnolog√≠as Cloud, Azure, Inteligencia Artificial, etc.
url: https://www.azurebrains.com
baseurl: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_drafts: false
